### ISSUE TITLE
URL Change made on Oct 21 has broken this plugin for deactivated Facebook accounts

### ISSUE THREAD

**Issue by chappy84** [meetfranz/recipe-messenger#12]
Facebook provides the functionality to deactivate your facebook account, but keep on using messenger

@adlk changed the URL in commit f46231166f8edfa7f71dfa5832b328cade30b145 from `messenger.com` to `facebook.com/messages`.

With the above mentioned account change, this has had the following consequences:
- If you login with the provided login screen, it re-activates your facebook account, and you go to the facebook feed, not messenger. This then requires people to deactivate their account again.
- To create a login session for just messenger, you must use the "Messenger" link at the bottom of the facebook login page.
- Every time Franz is opened, you're taken back to the facebook login page. To use the previous login session, you must use the "Messenger" link at the bottom of the page again.

This change was [questioned](https://github.com/meetfranz/recipe-messenger/commit/f46231166f8edfa7f71dfa5832b328cade30b145#r43692577) by @Kuzdo, but wasn't responded to.

It'd be good to know why the URL change itself was required?
Was this the only way to fix the login loop mentioned in the commit message?

**Comment by Kuzdo** [comment]
I changed for myself this link in file, and it's working for me all the time. I've never had a problem with login loop, and I'm use Franz with Messenger every day

**Comment by chappy84** [comment]
I have as-well.
Raising the issue I'm thinking about other users that don't necessarily know how to find the recipe, or edit json, but do want to use Franz. A login loop is obviously not good, but the above issue is also not good for users, and can un-knowingly put them in a situation where their main facebook account is re-activated without that being their intention.

**Comment by chappy84** [comment]
Anyone looking at the responses above, it's also worth noting that manually fixing in the `package.json` doesn't persist between plugin updates by Franz, so you either have to make the file immutable, potentially ignoring updates to that file by Franz, or have to manually change it back after each plugin update.

**Comment by chappy84** [comment]
This was fixed in bb0c910a011c083e63ee30dd96054875a0fa9276
