### ISSUE TITLE
Opening a link to Facebook in Messenger opens the link in Franz

### ISSUE THREAD

**Issue by jhoareau** [meetfranz/recipe-messenger#2]
**How to reproduce:**
1. Recieve/send a link to a Facebook video for example
2. Click on the title of the video

**Expected behavior:**
It should open the link in the browser, because the new Franz window does not have the right session settings for Facebook, therefore not being logged in.

**Franz version**: 5.0 beta 13, macOS. It used to work fine in Franz 4.

I guess you should make Facebook links open in Franz only if it's a call or something :)

**Comment by adlk** [comment]
This is an issue we have with the overall link handling. This should be resolved in the next couple of weeks with a Franz update.

**Comment by jhoareau** [comment]
@adlk Now it happens when clicking on a profile name, which is supposed to lead to the profile in the browser, but opens it inside Franz
