### ISSUE TITLE
When I close or restart Franz, Messenger isn't logged in and shows sign in page

### ISSUE THREAD

**Issue by the-glima** [meetfranz/recipe-messenger#4]
### Expected Behavior

When I close or restart Franz, Messenger service should keep me logged in like others recipes.

### Current Behavior

When I close or restart Franz, Messenger isn't logged in and shows sign in page.

### Steps to Reproduce

Log in Messenger, restart Franz and go to Messenger.

### Your Environment

Franz Version used: Version 5.0.0-beta.13 (5.0.0-beta.13.316)
Operating System and version: macOS High Sierra 10.13.1

**Comment by adlk** [comment]
Did you check the "stay logged in" option?

**Comment by the-glima** [comment]
@adlk apparently not 😅, my bad.
Everything is working fine.
