### ISSUE TITLE
Notification Center not working macOS 10.13.2

### ISSUE THREAD

**Issue by fye712** [meetfranz/recipe-messenger#5]
Same as https://github.com/meetfranz/franz/issues/377 except for messenger.

**Comment by dannyqiu** [comment]
When you click on the gear icon for messenger and go to settings, do you see this?
<img width="535" alt="screen shot 2017-12-27 at 5 56 14 pm" src="https://user-images.githubusercontent.com/1170755/34395570-4bcc0aac-eb2f-11e7-9590-524f9868a91a.png">

**Comment by drewatk** [comment]
Having the same issue
@dannyqiu Here's what my Messenger settings look like:
<img width="911" alt="screen shot 2018-01-03 at 8 09 38 pm" src="https://user-images.githubusercontent.com/7624911/34546476-188f86f8-f0c2-11e7-945c-c82da86b00dd.png">

Franz Version: 5.0.0-beta.14

**Comment by dannyqiu** [comment]
The screenshot from earlier is located in the Messenger specific settings:
<img width="261" alt="screen shot 2018-01-03 at 8 38 48 pm" src="https://user-images.githubusercontent.com/1170755/34547032-1ecdfbf4-f0c6-11e7-8044-9c709ff81283.png">

**Comment by drewatk** [comment]
Thanks for the clarification. Turning that on fixed it!

**Comment by adlk** [comment]
Merged and published @dannyqiu's fix! Thank you for taking care of this.
